### ISSUE TITLE
Parse a playbook execution log

### ISSUE THREAD

**Issue by xanderjjj** [haidaraM/ansible-playbook-grapher#12]
It would be nice as a debugging tool if we could parse a playbook execution log and for a given host in the inventory, and colourise the tasks in the graph depending on their execution result (successful, skipped, changed, failed).
This could also be used to hide tasks that don't get run.
Suggested args --execution-log, --hostname and --hide-skipped

**Comment by haidaraM** [comment]
Hey hey,

Unfortunately, I'm not going to work on this anytime soon. If someone still finds this feature useful, do not hesitate to comment or submit a PR :-)
