### ISSUE TITLE
[Feature request] Variable mapping option

### ISSUE THREAD

**Issue by orangecuse44** [haidaraM/ansible-playbook-grapher#128]
I'm looking to document a large playbook and documenting where variables are declared, and where they're used, has been difficult.

I'd like to see an option to map where variables are defined and where in the playbook they're used. More specifically, if I know I've declared variables in `<role-name>/meta/main.yml`, I want to tell the grapher to start in `<role-name>/meta/main.yml` and map to where they are used within that role (or, in other roles).

**Comment by haidaraM** [comment]
Hi @orangecuse44 
If I understand correctly, you want a new kind of graph highlighting variables usage in the playbook or something else?

**Comment by haidaraM** [comment]
Closing this. Feel free to re-open this if you still need this feature
