### ISSUE TITLE
[Feature request] generate mermaid instead of images

### ISSUE THREAD

**Issue by briantist** [haidaraM/ansible-playbook-grapher#137]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
It would be nice to be able to generate mermaid instead of SVG/images, so we could embed the output directly into places that support it , like on GitHub.

quick example:

```mermaid
graph TD
    A[Thievery] -->|Get money| B(Go shopping)
    B --> C{Let me think}
    C -->|One| D[Laptop]
    C -->|Two| E[iPhone]
    C -->|Three| F[fa:fa-car Car]
```

**Comment by haidaraM** [comment]
I actually have this on my mind since a few months but was wondering if it would be useful or not for users. 

Will see what I can do. Should be doable

**Comment by haidaraM** [comment]
@briantist You can take a look at some graphs in mermaid here: https://github.com/haidaraM/ansible-playbook-grapher/actions/runs/4954157710/attempts/1#summary-13421932864

Still need to do more tests but it should look like something like this

**Comment by briantist** [comment]
wow! that's looking really neat @haidaraM , thank you!

**Comment by cocoonkid** [comment]
YES YES!

**Comment by haidaraM** [comment]
Just released a preview version. Let me know what you think: `pip install ansible-playbook-grapher==2.0.0.dev0`

**Comment by haidaraM** [comment]
Closing this. Released in https://pypi.org/project/ansible-playbook-grapher/2.0.0/. 

Feel free to open a new issue or comment this one in case of any errors.
