### ISSUE TITLE
Add support for block within playbook

### ISSUE THREAD

**Issue by lin1000** [haidaraM/ansible-playbook-grapher#14]
It will be quite helpful to visualize "block" directive in playbook.

**Comment by haidaraM** [comment]
Is it somehow related to #13 ? Or you want to distinguish "block" in the graph ?

**Comment by lin1000** [comment]
Hi haidaraM, apologize for late feedback.  For example, usually I wrote several tasks and group it together by the "block" section.

- name: "create multiple deployment folders"
  block:
  - name: "Setting Fact Deployment Folder {{ deployment_path }}"
    set_fact: 
      deployment_path : "{{ inventory_dir }}/deployment"
  - name: "Checking deployment folders"
    stat:
      path: "{{ item }}"
    register: folder_stats
    with_items:
    - ["{{ deployment_path }}/mescore","{{ deployment_path }}/meslog"]
  - name: "Creating multiple folders without disturbing previous permissions"
    file:
      path: "{{item.item}}"
      state: directory
      mode: 0755
    when: item.stat.exists == false
    with_items:
    - "{{folder_stats.results}}"

**Comment by haidaraM** [comment]
No worries :-)

So you want to see somehow this block in the graph ?

**Comment by lin1000** [comment]
YES!

**Comment by haidaraM** [comment]
Implemented this in #86 
<img width="2047" alt="Capture d’écran 2021-09-26 à 16 26 15" src="https://user-images.githubusercontent.com/9849996/134811989-ea5c3f0e-28a5-495e-ad4d-67ec63186e4c.png">
