### ISSUE TITLE
[Bug report] Please bump version of ansible-core

### ISSUE THREAD

**Issue by cocoonkid** [haidaraM/ansible-playbook-grapher#145]
```
ansible-playbook-grapher) (2.21)
Installing collected packages: ansible-core, ansible-playbook-grapher
  Attempting uninstall: ansible-core
    Found existing installation: ansible-core 2.14.5
    Uninstalling ansible-core-2.14.5:
      Successfully uninstalled ansible-core-2.14.5
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
ansible 7.5.0 requires ansible-core~=2.14.5, but you have ansible-core 2.12.10 which is incompatible.
```

Thank you so much!

**Comment by haidaraM** [comment]
Weird! Are you using a virtualenv to install the grapher? The grapher only requires `ansible-core` and not `ansible`. From what I see in the [requirements](https://github.com/haidaraM/ansible-playbook-grapher/blob/main/requirements.txt#L1), there shouldn't be a conflict.

**Comment by cocoonkid** [comment]
No. not using a venv.  I used asdf-vm to manage versions but this is not the same as venv or pyenv or poetry (favorite).
I will try again on the weekend and report back with more details.

**Comment by cocoonkid** [comment]
@haidaraM 

![image](https://github.com/haidaraM/ansible-playbook-grapher/assets/43231640/ec128744-6adb-4e6d-9bca-2c06210e265f)
![image](https://github.com/haidaraM/ansible-playbook-grapher/assets/43231640/5831bed9-a0ad-4497-9ad2-ef304fd1597a)

![image](https://github.com/haidaraM/ansible-playbook-grapher/assets/43231640/333942e8-f2af-46fe-b205-53623dfed5dc)


I install the package with pip but somehow the version requirement is different.

Not sure why this is...

**Comment by cocoonkid** [comment]
I think I found it. The metadata is deprecated. 
![image](https://github.com/haidaraM/ansible-playbook-grapher/assets/43231640/a4b70c9c-6ba1-48d2-90d4-c54cfb2b1300)

Maybe you can put up a new relrease?

Thanks so much!!

**Comment by cocoonkid** [comment]
I just went with `pip install ansible-playbook-grapher==2.0.0.dev0` ;-)

**Comment by haidaraM** [comment]
> I think I found it. The metadata is deprecated. ![image](https://user-images.githubusercontent.com/43231640/241733324-a4b70c9c-6ba1-48d2-90d4-c54cfb2b1300.png)
> 
> Maybe you can put up a new release?
> 
> Thanks so much!!

What do you mean by `The metadata is deprecated` ? 

Also, fixed a small bug. The latest release is now `2.0.0.dev2`

**Comment by haidaraM** [comment]
Oh I see. Closing this then. Will release a final version in the following days.
