### ISSUE TITLE
[Feature request] Include inventory graphing and make this the ansible-super-grapher

### ISSUE THREAD

**Issue by cocoonkid** [haidaraM/ansible-playbook-grapher#148]
Since [Inventory Grapher](https://github.com/willthames/ansible-inventory-grapher) looks abandoned 
it would be so amazing to have the same opportunity here.

Thanks for consideration!

**Comment by haidaraM** [comment]
Since there were some recent commits on the Inventory grapher and the impact of implementing this inside this project, not sure if I will implement this.

Happy to accept contributions if someone finds this useful. Otherwise, I'm going to close this issue by the end of this year :-)

**Comment by haidaraM** [comment]
Closing this as not planned. Future contributions are welcome!
