### ISSUE TITLE
Does the tool have run playbooks first?

### ISSUE THREAD

**Issue by ajubakhanji** [haidaraM/ansible-playbook-grapher#162]
Hi, 

I was testing the ansible-playbook-grapher on an ansible playbooks. From my understanding, the tool is meant to simply graph a playbook and provide you with a graphical overview. However, when attempting to do so, it appeared that the tool attempts to run the playbook first. Is that correct or have I misunderstood the tool's purpose?

I hope you can clarify this confusion of mine.

Thank you in advance!

**Comment by haidaraM** [comment]
Hi @ajubakhanji,

The tool does NOT run the playbook but only parses it using Ansible built-in features. However, it tries to interpolate some variables during the parsing if possible.

What made you think that it runs the playbook?

**Comment by ajubakhanji** [comment]
Hi again, thank you for your quick response!

The reason I thought it was attempting to run the playbook is due to an error that was raised upon attempting to render a graph. However, I now understand that is not due to the tool attempting to run the playbook but rather attempting to parse it. 

Thank you for taking the time to clarify this. Closing this issue now!

**Comment by haidaraM** [comment]
Welcome :-)
