### ISSUE TITLE
[Feature request]  Add a key to hide plays(tasks) without any role

### ISSUE THREAD

**Issue by fireman777** [haidaraM/ansible-playbook-grapher#176]
**Is your feature request related to a problem? Please describe.**
It would be great if there would be an opportunity to hide plays(tasks) without any role.

**Describe the solution you'd like**
Please consider adding a key (for example --hide-tasks-without-roles) to ansible-playbook-grapher to hide plays(tasks) without any role.

![image](https://github.com/haidaraM/ansible-playbook-grapher/assets/39376634/91e54d1d-dfcd-4ccf-9f6c-a3f5fd1b9951)

**Comment by haidaraM** [comment]
Hi, 

Trying to understand the use case: basically, you just want to display the roles (and their tasks) without any standalone tasks?

**Comment by fireman777** [comment]
Hi @haidaraM,
Sorry for confusing you from my side. I mean plays. Here is a picture where I showed what I mean:
![IMG_150324_01](https://github.com/haidaraM/ansible-playbook-grapher/assets/39376634/b035af16-b247-45ce-85c1-691fcd9c9e9f)

**Comment by haidaraM** [comment]
No problem :-) 

I got the idea. What do you think about just excluding plays that end up with no tasks at all (not only roles)?

**Comment by fireman777** [comment]
Hi @haidaraM,
I think it's a good idea, but I would separate these two options, for example:
**--hide-plays-without-roles**: hide (don't show) plays without any role;
**--hide-plays-without-tasks**: hide (don't show) plays without any task.
I can explain why it can be useful: example, in playbook  have lot of plays and a lot of combination of tags. Depending on tag that we can select, we will have quite different pictures (graphs). It's important at this moment to have the ability to exclude some plays without roles/tasks, because some projects may have hundreds of plays.
So, my mind is that it's better to have two options: --hide-plays-without-roles and --hide-plays-without-tasks.
We would be very thankful if you could implement such functionality.

**Comment by haidaraM** [comment]
Interesting. Makes sense! 

Should be easily doable!

**Comment by haidaraM** [comment]
> --hide-plays-without-roles: hide (don't show) plays without any role;

This also needs to consider the usages of `include_role` inside the play. That means I need to consider all the tasks inside the play to decide if I need to display the play or not (not only the roles set on the play level).

**Comment by fireman777** [comment]
Thank you for your willingness to help. Your project is very interesting and in my opinion, has a great future.

**Comment by haidaraM** [comment]
Thanks for the feedback, I appreciate it :-)

**Comment by haidaraM** [comment]
Can you give a try to `pip install "ansible-playbook-grapher @ git+https://github.com/haidaraM/ansible-playbook-grapher@hide-plays"` and let me know. I added two new flags. 

See https://github.com/haidaraM/ansible-playbook-grapher/pull/177

**Comment by fireman777** [comment]
Hi @haidaraM, I've tested already and it works as expected.
I want to thank you and wish you and your project a powerfull future.
Thanks a lot.

**Comment by haidaraM** [comment]
Closing this. Will be released in the next version (following days/weeks).
