### ISSUE TITLE
tags inside a role are not handled the same as ansible-playbook does

### ISSUE THREAD

**Issue by Geertsky** [haidaraM/ansible-playbook-grapher#226]
Again, thanks for your great tool! I love it!

**Describe the bug**
I've noticed that when I have a playbook where a role is imported, and the role contains a task with a tag, I can call the task using `ansible-playbook -t this_is_a_tag playbook-test.yml`. When I however run `ansible-playbook-grapher --include-role-tasks -t this_is_a_tag playbook-test.yml` The tagged task is never seen as the role is excluded due to the fact that the role isn't tagged.

**To Reproduce**
**playbook-test.yml**

```
---

- name: test
  hosts: localhost
  gather_facts: false
  roles:
    - role: test
```

**test/tasks/main.yml**

```
---

- name: Task with a tag
  ansible.builtin.debug:
    msg: Msg from a task with a tag
  tags:
    - this_is_a_tag
```

**ansible-playbook -t this_is_a_tag --list-tasks playbook-test.yml**

```
ansible-playbook -t this_is_a_tag --list-tasks playbook-test.yml

  play #1 (localhost): test     TAGS: []
    tasks:
      test : Task with a tag    TAGS: [this_is_a_tag]
```

**ansible-playbook-grapher --include-role-tasks -t this_is_a_tag playbook-test.yml -vv**

```
ansible-playbook-grapher --include-role-tasks -t this_is_a_tag playbook-test.yml -vv
Parsing Play: test (1)
Parsing pre_tasks...
Parsing roles...
The role 'test' is skipped due to the tags.
Parsing tasks...
Parsing post_tasks...
0 pre_task(s) added to the graph.
0 role(s) added to the play
0 task(s) added to the play
0 post_task(s) added to the play
Rendering the graph...
```

**Expected behavior**
Same behaviour as `ansible-playbook`

**Versions:**
Outputs of :
 - `ansible --version`

``` 
ansible [core 2.17.6]
  config file = ansible.cfg
  configured module search path = ['/home/geertsky/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/geertsky/miniforge3/envs/ansible-2.17.6-playbook-grapher/lib/python3.13/site-packages/ansible
  ansible collection location = /home/geertsky/.ansible/collections:/usr/share/ansible/collections
  executable location = /home/geertsky/miniforge3/envs/ansible-2.17.6-playbook-grapher/bin/ansible
  python version = 3.13.1 | packaged by conda-forge | (main, Dec  5 2024, 21:23:54) [GCC 13.3.0] (/home/geertsky/miniforge3/envs/ansible-2.17.6-playbook-grapher/bin/python3.13)
  jinja version = 3.1.4
  libyaml = True
```
 - `ansible-playbook-grapher --version`

```
ansible-playbook-grapher 2.6.0 (with ansible 2.17.6)
```

**Additional context**

**Comment by haidaraM** [comment]
This is in fact a bug. Will have to refactor/review the parser to properly fix this.

**Comment by Geertsky** [comment]
Great!! Works perfectly!
Thanks allot.
