### ISSUE TITLE
[Bug report] Doesnt support ansible2.9

### ISSUE THREAD

**Issue by narimantos** [haidaraM/ansible-playbook-grapher#23]
The grapher doesnt work with ansible 2.9.0 

**To Reproduce**
pip install ansible=2.9.0

**Comment by haidaraM** [comment]
Looks like they have changed their command line parser. I have added a test for Ansible 2.9: https://travis-ci.org/haidaraM/ansible-playbook-grapher/builds/611384865?utm_source=github_status&utm_medium=notification

**Comment by haidaraM** [comment]
Fixed. Will be released in the next version
