### ISSUE TITLE
[Feature request] graph options and hidden  NOT_TAGGED

### ISSUE THREAD

**Issue by mysiki** [haidaraM/ansible-playbook-grapher#24]
Hi,

I have few question than can be feature maybe :) :
- Graph option : It's not possible to provide option about render like in inspired project https://github.com/willthames/ansible-inventory-grapher (- a arg in this project) ? 
- When I run it with -t or --skip-tags, its normal that all the tasks are display but just with different opacity and not clickable ? It's not possible to not export skipped tags ? 

Thank, br

**Comment by haidaraM** [comment]
Hi,

- Graph option: I have thought about doing that. I will see if it's possible to do that. The rendering options (shapes, lines) are currently directly integrated in the graph
- It's normal: I chose to do it this way. It should be possible to completely skip them instead of reducing their opacity.

**Comment by mysiki** [comment]
Thank for reply, for me the second point is really important. I have many many tasks and subplaybook in my project, generate graph without skip tasks will be really great. If you find some time for work on it, ping me, I can make some test really fast. 

> It's normal: I chose to do it this way. It should be possible to completely skip them instead of reducing their opacity.

**Comment by drzraf** [comment]
I also suggest to omit tasks having `when: False`.

**Comment by haidaraM** [comment]
@mysiki I'm thinking of respecting the value of `display_skipped_hosts` in ansible.cfg or `ANSIBLE_DISPLAY_SKIPPED_HOSTS` env var (https://docs.ansible.com/ansible/latest/reference_appendices/config.html#display-skipped-hosts). 
If false/0, I will remove the corresponding tasks from the graph.

The idea is to be as close as possible to Ansible's behavior.

**Comment by haidaraM** [comment]
@drzraf It should be possible to omit these tasks too

**Comment by mysiki** [comment]
> 
> 
> @mysiki I'm thinking of respecting the value of `display_skipped_hosts` in ansible.cfg or `ANSIBLE_DISPLAY_SKIPPED_HOSTS` env var (https://docs.ansible.com/ansible/latest/reference_appendices/config.html#display-skipped-hosts).
> If false/0, I will remove the corresponding tasks from the graph.
> 
> The idea is to be as close as possible to Ansible's behavior.

Oh yes, if it simple to use this it avoid to add command switch and many piece of code. And we have env var for manage it so I think it's good. 
Just think to add it in documentation, because depend of callback using, some do not use this variable.

**Comment by haidaraM** [comment]
After I thought about it, I will not use the value of `display_skipped_hosts`. By default, Ansible doesn't display skipped tasks when using the option "-t" or "--skip-tasks". 

I confused this behavior with the "when" condition when the tasks are displayed even though they are not run.

**Comment by mysiki** [comment]
ok, you are right. So you just doesn't display skipped task (?). Can I test the PR ?

**Comment by haidaraM** [comment]
Yes. You can test it

**Comment by mysiki** [comment]
Great ! It work for me. I test it with ansible 2.8. 

I don't make all possible test, only some classic -t and --skip-tags. But the render is great !

**Comment by haidaraM** [comment]
Released in 0.10.0
