### ISSUE TITLE
Upgrade lxml to some newer version

### ISSUE THREAD

**Issue by dmpe** [haidaraM/ansible-playbook-grapher#28]
Can we please upgrade dependencies for this amazing plugin?

https://github.com/haidaraM/ansible-playbook-grapher/blob/master/requirements.txt

Particularly `lxml` would be nice, i.e. using latest possible version. 

Example: I currently use [ansible vmware automation sdk](https://github.com/vmware/vsphere-automation-sdk-python) and that installs lxml 4.5. Thus, there is a conflict using this plugin.

**Comment by haidaraM** [comment]
Released in 0.9.3
