### ISSUE TITLE
[Feature request] Add support for role dependencies

### ISSUE THREAD

**Issue by sboisson** [haidaraM/ansible-playbook-grapher#39]
It would be great if the graph would include role dependencies (from meta/main.yml of each roles, including the one imported from ansible Galaxy)

**Comment by jordibass** [comment]
I will include on this request the **include_role** directive inside the tasks.
Regards

**Comment by haidaraM** [comment]
Will see if I can fetch the role dependencies when reading the playbook.

@jordibass I post a [this comment](https://github.com/haidaraM/ansible-playbook-grapher/issues/22#issuecomment-551754877) regarding the *include_role* directive.

**Comment by ccamacho** [comment]
@haidaraM the include_role is an incredibly common case when including tasks from roles, is there a way to workaround this in order to not append the tasks of the role as mere "tasks" instead splitting them in their corresponding roles?

**Comment by haidaraM** [comment]
@ccamacho Will see if I can find a way to manage `include_role` as a classic role. Just marked #22 as feature requests

**Comment by haidaraM** [comment]
@ccamacho The behavior of `include_role` have been changed. See my comment: https://github.com/haidaraM/ansible-playbook-grapher/issues/22#issuecomment-920357882

**Comment by haidaraM** [comment]
After reviewing, it's already supported by the grapher. I added a test case for it. Feel free to comment or create a new issue if you have some use cases that are not supported.
