### ISSUE TITLE
Refactor: make the grapher usable as a library

### ISSUE THREAD

**Issue by haidaraM** [haidaraM/ansible-playbook-grapher#45]
I wrote most of the grapher almost 7 years ago in 2017 and lot of things happened since 😄 

Currently, the Grapher is tightly coupled to the CLI. This makes it difficult to use it as a library inside another project. Also the `Grapher` is a little bit complicated: thinking of splitting it. I also want to make the graph customizable by not hardcoding the shapes, layout and make the post processor more extensible.

So this issue is here to track the related changes. The outcome of these changes will be the version ~v1.0.0~ ~v2.0.0~ v3.0.0 of the grapher?

**Comment by haidaraM** [comment]
The code is now cleaner. Will update the Readme with an example to integrate this in an existing project. Meanwhile, you can take how the [CLI works as an example](https://github.com/haidaraM/ansible-playbook-grapher/blob/7a92fe8e7a2701d2e27a746e405c6df162992146/ansibleplaybookgrapher/cli.py#L41-L57).

**Comment by haidaraM** [comment]
For those following this issue: while the code can be used in another project, keep in mind that the internal API is not stable yet. I will likely refactor the internal of the grapher in the following versions. The Parser should not change that much.

**Comment by ShanePresley** [comment]
A renderer that dumps the output of the parser into json for consumption by third-party tools would be really useful.

**Comment by haidaraM** [comment]
@ShanePresley This should be doable. Let me track that as a separate feature request: https://github.com/haidaraM/ansible-playbook-grapher/issues/192

**Comment by haidaraM** [comment]
> @ShanePresley This should be doable. Let me track that as a separate feature request: #192

Will be released in the following days.

**Comment by haidaraM** [comment]
The project has a JSON renderer since the version [v2.3.0](https://github.com/haidaraM/ansible-playbook-grapher/releases/tag/v2.3.0)

---

Some updates: 

- As Ansible itself is primarily CLI-driven, building a reusable library on top of it like I planned to do is far from trivial. As such, I don't think I will pursue that goal anymore. **The grapher will remain CLI-driven** unless people are willing to contribute to refactor the project. 
- You can take the entrypoint as example if you want to integrate this into another project but no guarantee regarding the interfaces (minor version of the grapher can change the signatures of the functions and methods). 
- You can use the JSON renderer if you are only interested in getting a graph representation of your playbooks. There is [an versioned associated JSON schema](https://github.com/haidaraM/ansible-playbook-grapher/blob/main/tests/fixtures/json-schemas/v1.json) with this renderer. Breaking changes will increase the version number of the schema. 

As such, I will close this issue by the end of the year.
