### ISSUE TITLE
Clicking on a node should open the corresponding file

### ISSUE THREAD

**Issue by sonulohani** [haidaraM/ansible-playbook-grapher#68]
**Is your feature request related to a problem? Please describe.**
Sometimes when I try to understand a bunch of ansible playbooks, I want to navigate to the playbook that I am looking in the graph. Currently I do it by doing find tool but its very hectic. It would be much better If I click on the node and it should open the file corresponding to that node.

**Describe the solution you'd like**
It wouldn't be difficult to implement this feature. Just a hint, you could use: `graph.attr("node", URL="file name")`

**Describe alternatives you've considered**
I dont know yet, will update soon if have any

**Comment by haidaraM** [comment]
Interesting feature! Currently, when you click on a node, the related nodes are highlighted. 

Will need to change that behavior maybe

**Comment by thetopnach** [comment]
+1 on the feature request. This feature would take it to the next level!

**Comment by haidaraM** [comment]
Just start working on this but I'm wondering how I should open the file :
 - Read the file and show it's content in a new tab
 - or ?

With this first implementation, when clicking on tasks, the browser tries to download the file. I guess it's because it doesn't know what to do with the yml file.

**Comment by thetopnach** [comment]
Could make a html file with the content of the yaml file with line numbers..

**Comment by haidaraM** [comment]
How could I show this file: in a modal or something else ? I'm not sure how I could "open" the corresponding file in the browser (if the SVG is open inside a browser).

I already have the filename and the line number in my graph representation.

**Comment by haidaraM** [comment]
This is almost implemented in https://github.com/haidaraM/ansible-playbook-grapher/issues/68. You will have the options to open the nodes inside the browser (when possible) or in Vscode using protocol handlers. I haven't seen yet others IDEs supporting protocol handlers like Vscode... I will add an option to provide your own "protocol format" to open the nodes. 

You can test it with `pip install git+https://github.com/haidaraM/ansible-playbook-grapher@feat/openNodeFile`

**Comment by haidaraM** [comment]
Will be released in the next version.
